CREATE TABLE users(
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    surname text NOT NULL,
    birth_date DATE,
    login text NOT NULL UNIQUE,
    password text NOT NULL,
    address text
);